---
title: "Spatial-Temporal Distribution of Kinkajous in a Balsa Tree"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:\\Users\\Nele\\Documents\\GitHub\\Balsa_Spatial_Analysis')
library(tidyverse)
library(lubridate)
library(sf)
library(dplyr)
library(ggplot2)
library(scales)
library(nlme)
```

```{r helper_functions}
get_study_day_and_time <- function(Datetime_string, study_start) {
  #study start must include the approximate start time of evening observations if overnight follows are to be binned into the correct study day
  datetime_vector <- strsplit(Datetime_string, split = "")[[1]]
  date1 <- paste(paste(datetime_vector[1:6], collapse = ""), 
                "20", 
                paste(datetime_vector[7:8], collapse = ""), sep = "") %>% as.POSIXct(format = "%d-%m-%Y", tz = "America/Panama")
  time1 = paste(datetime_vector[9:10], collapse = "")
  study_day = difftime(date1, study_start, units = "days") %>% floor()
  return(list(study_day, time1))
}

get_kinkMinutesPerHour <- function(count_data, categories = 6) {
  #default value for categories assumes count data has 6 rows per observational minute, representing 3 Regions x 2 states (hidden or visible)
  minutes_per_hour = (sum(count_data)/(length(count_data)/categories)) * 60
  return(minutes_per_hour)
}

get_growth_index <- function(time_series) {
  removed = 0
  while(time_series[1] == 0) {
    time_series <- time_series[-1]
    warning("initial observation removed due to value of 0")
    removed = removed + 1
  }
  growth_index <- ((time_series-time_series[1])/time_series[1]) * 100
  return(c(rep(NA, times = removed), growth_index))
}
```

```{r data_load, message = FALSE}
file_names <- dir("./DATA/raw/Kinkajou_Scans_Nele", pattern = ".csv")

video_metadata_location <- "./DATA/raw/Video_metadata/video_file_timestamp_metadata_cam1.txt"
dir()
video_metadata <- readChar(con = video_metadata_location, nchars = file.info(video_metadata_location)$size)
video_metadata <- str_split(video_metadata, pattern = "Folder: ")[[1]][-1] #break all metadata into strings for each observation period (and remove preceding empty character)
video_metadata <- str_split(video_metadata, pattern =  "start = ") #find the start time of all files
start_timestamps <- sapply(video_metadata, function(X) str_split(X[2], pattern = "\r")[[1]][1]) #extract start time of first file and remove all extra data
start_timestamps <- as.POSIXct(start_timestamps, format = "%Y-%m-%d_%H-%M-%S", tz = "GMT")
start_timestamps <- with_tz(start_timestamps, "America/Panama")


all_kinkajou_scans <-  c()
Jan_22_check = FALSE #used later to parse two video files that started on the same day (one AM one PM)

for(file_name in file_names) {
  scan_data <- read_csv(paste("./DATA/raw/Kinkajou_Scans_Nele/", file_name, sep = ""), skip = 1, progress = FALSE)
  colnames(scan_data) <- c("timestamp", "Region1_visible", "Region1_hidden", "Region2_visible", "Region2_hidden", "Region3_visible", "Region3_hidden", "Kinkajou_Notes", "Video_Notes", "Extraneous")
  scan_data <- scan_data[complete.cases(scan_data$timestamp),] %>% select(! Extraneous)
  start_date <- str_split(file_name ,pattern = "_Cam")[[1]][1] #str_split returns a list of string components. We want the first (and only) element of this list - then the first string element in this list gives the date
  start_date <- as.POSIXct(paste("20", start_date, sep = ""), format = "%Y_%m_%d") #date needs all 4 digits
  start_timestamp <- start_timestamps[which(date(start_timestamps) == start_date)]
  #Two video files started on Jan 22nd, one AM and one PM. Because this is the ONLY date where this occurred, I implemented a quick and dirty check to parse the AM file first and the PM file second, below
  if (length(start_timestamp) > 1)
      if (! Jan_22_check) {
        start_timestamp <- start_timestamp[1]
        Jan_22_check <-  TRUE
      } else start_timestamp <- start_timestamp[2]
  #end Jan 22 case
  scan_data$timestamp <- start_timestamp + period_to_seconds(hms(scan_data$timestamp))
  scan_data$Study_night <- round(as.numeric(start_timestamp - start_timestamps[1], units = "days"), digits = 0)
  all_kinkajou_scans <- rbind(all_kinkajou_scans, scan_data)
}
```



```{r data_prep}
#convert empty count cells (NAs) to 0
count_data <- all_kinkajou_scans[,2:7] # columns 2 through 7 are the count data columns, we want NAs in the notes columns
count_data[is.na(count_data)] <- 0
all_kinkajou_scans[,2:7] <- count_data

#The data as read contain the TOTAL number of kinkajous and the number of those total that are hidden. As suggested by the new names given to the columns in this data structure, we want the count of visible and hidden kinkajous, not the total. The adjustment is made below
all_kinkajou_scans <- mutate(all_kinkajou_scans, Region1_visible = Region1_visible - Region1_hidden, Region2_visible = Region2_visible - Region2_hidden, Region3_visible = Region3_visible - Region3_hidden)

#pivot dataframe to long format for easy usage in ggplot
all_kinkajou_scans_long <- pivot_longer(all_kinkajou_scans,
                                   cols = Region1_visible:Region3_hidden,
                                   names_to = c("Region", "Visibility"),
                                   names_sep = "_",
                                   values_to = "Count")

all_kinkajou_scans_long$Region <- sapply(all_kinkajou_scans_long$Region, switch, "Region1" = "1", "Region2" = "2", "Region3" = "3") %>% factor()

write.csv(all_kinkajou_scans_long, "./DATA/processed/all_kinkajou_scans.csv")
```

```{r data_visuals}
#We create a series of plots with increasing complexity as a demonstration of building visualizatins in ggplot
plot_data <- ggplot(all_kinkajou_scans_long)

plot_data + geom_col(aes(x = Region, y = Count))

ggplot(all_kinkajou_scans_long) +
  geom_col(aes(x = Region, y = Count, fill = Visibility)) +
  facet_wrap(~Study_night)
```

```{r load_balsa_data, message = FALSE}
files = strsplit(dir("./DATA/raw/Flower_geopackages"), split = "[.]") #seperate filenames from extensions for all files in folder
files = files[sapply(files, function(X) X[2] == "gpkg")] #reduce file list only to gpkg files
geopackages <- vector("list", length = length(files))
for(i in seq_along(files)){
  flower_sf <- st_read(paste("./DATA/raw/Flower_geopackages/", files[[i]][1], ".", files[[i]][2], sep = ""), quiet = TRUE)
  flower_sf$Region <- strsplit(files[[i]][1], split = NULL)[[1]] %>% last() %>% as.numeric() + 1 #QGIS labelled regioning grouping outputs at 0 (last element of savefile string); add one to get region labels that match kinkajou data
  flower_sf$Date <- strsplit(files[[i]][1], split = "_")[[1]][2]
  geopackages[[i]] <- flower_sf
}
all_upflowers <- do.call(rbind, geopackages)
all_upflowers$Region <- factor(all_upflowers$Region)

#Drone flights are labelled by a character with date and time of scan. The date needs to be converted to a study day variable and the time put into its own column
all_upflowers <- all_upflowers %>% mutate(Study_night = sapply(Date, function(X) get_study_day_and_time(X, study_start = as.POSIXct("2019-12-14 18:00:00", tz = "America/Panama"))[[1]]),
                                          Time = factor(sapply(Date, function(X) get_study_day_and_time(X, study_start= as.POSIXct("2019-12-14 18:00:00", tz = "America/Panama")) [[2]])))

```

```{r viz_by_day}
ggplot(all_upflowers, aes(x = Study_night, color = Time)) + geom_line(stat = "count") + geom_point(stat = "count") +
  theme_classic() +
  labs(title = "Upright Flowers Counted")

ggplot(all_kinkajou_scans_long, aes(x = Study_night, y = Count)) + stat_summary(fun = "get_kinkMinutesPerHour", geom = "line") + stat_summary(fun = "get_kinkMinutesPerHour", geom = "point") +
  theme_classic() +
  labs(title = "Time Spent in Crown", y = "Kinkajou Minutes per Hour")

all_upflowers <- all_upflowers %>% filter(Time == "AM" | !Study_night %in% c(23, 26, 25, 32)) %>% #remove data from images marked in notes as poor quality photos
  filter(Time == "PM" | !Study_night %in% c(20,21)) #remove data from images marked in notes as poor quality photos


  
flower_counts <- all_upflowers %>% 
  group_by(Study_night, Time) %>% summarise(Count = n()) %>% 
  mutate(Study_night = Study_night - (Time == "AM")) %>% #study night is based on date, but we want to match AM recordings to previous PM recordins, so we subtract one from all AM study night values
  group_by(Study_night) %>% #where there were good photos for both AM and PM, we will use the mean flower count which is achieved by grouping and summariying
  summarise(Count = mean(Count)) %>% 
  transform(Growth = get_growth_index(Count)) #used to visually compare changes in flower count to changes in kinkajou residency without bias


kinkajou_counts <- all_kinkajou_scans_long %>% group_by(Study_night) %>% summarise(Minutes_Per_Hour = get_kinkMinutesPerHour(Count)) %>% transform(Growth = get_growth_index(Minutes_Per_Hour))
combined_data <- merge(flower_counts, kinkajou_counts, by = "Study_night", all = TRUE)

ggplot(flower_counts, aes(x = Study_night, y = Growth)) + 
  geom_line(stat = "identity") +
  geom_point(stat = "identity") +
  geom_line(data = kinkajou_counts, stat = "identity", linetype = "dashed") +
  geom_point(data = kinkajou_counts, stat = "identity") +
  theme_classic() +
  scale_color_discrete(name = "Flower Count") +
  labs(title = "Growth in Minutes per Hour Kinkajous spend in a balsa crown (black dotted) \n and balsa flower counts (solid) over study period",
       y = "Growth (%)",
       x = "Study Night")

ggplot(all_upflowers) + geom_sf(aes(color = factor(Date), shape = factor(Region)))
ggplot(all_upflowers) + geom_bar(aes(x = factor(Region))) + facet_wrap(~Date)

ggplot(flower_counts, aes(x = Study_night, y = Growth)) + 
  geom_line(aes(linetype = "Flower Count"), stat = "identity") +
  geom_point(stat = "identity") +
  geom_line(mapping = aes(linetype = "Residence Time"), data = kinkajou_counts, stat = "identity") +
  geom_point(data = kinkajou_counts, stat = "identity") +
  theme_classic() +
  scale_color_discrete(name = "Flower Count") +
  scale_linetype_manual(values = c("Flower Count" = "solid", "Residence Time" = "dashed")) +
  labs(#title = "Growth in Minutes per Hour Kinkajous spend in a balsa crown (black dotted) \n and balsa flower counts (solid) over study period",
       y = "Growth (%)",
       x = "Study Night")
```

```{r analysis_by_region}
flower_counts_region <- all_upflowers %>% mutate(Study_night = Study_night - (Time == "AM")) %>% 
  group_by(Study_night, Region) %>% 
  summarise(Count = n()) %>% 
  group_by(Study_night, Region) %>% 
  mutate(Count = mean(Count)) %>% 
  group_by(Region) %>% group_modify(~ transform(.x, Growth = get_growth_index(Count))) %>% 
  ungroup()

kinkajou_counts_region <- all_kinkajou_scans_long %>% group_by(Study_night, Region) %>% summarise(Minutes_Per_Hour = get_kinkMinutesPerHour(Count, categories = 2)) %>% group_by(Region) %>% group_modify(~ transform(.x, Growth = get_growth_index(Minutes_Per_Hour)))

ggplot(flower_counts_region, aes(x = Study_night, y = Count, color = Region)) + geom_line(stat = "identity") + geom_point(stat = "identity") +
  theme_classic() +
  labs(title = "Flower Counts by Region")

ggplot(kinkajou_counts_region, aes(x = Study_night, y = Minutes_Per_Hour, color = Region)) + geom_line(stat = "identity") + geom_point(stat = "identity") +
  theme_classic() +
  labs(title = "Time Spent by Kinkajous in Region")

ggplot(flower_counts_region, aes(x = Study_night, y = Growth)) + geom_line(color = "green3", stat = "identity") + geom_point(stat = "identity", color = "green3") +
  geom_line(data = kinkajou_counts_region, aes(color = "black")) + geom_point(data = kinkajou_counts_region, color = "black") +
  theme_classic() + 
  facet_wrap(~Region, labeller = "label_both") +
  theme(legend.position = "bottom") +
  scale_color_manual(name = "", values = c("Flower Count" = "green3", "Kinkajou Minutes Per Hour" = "black")) +
  labs(#title = "Growth in Minutes per Hour Kinkajous spend in a balsa crown (black) \n and balsa flower counts (solid) over study period",
       y = "Growth (%)",
       x = "Study Night")
```



```{r summary statistics}
#means and standard deviation of kinkajou movement
mean_residence <- mean(kinkajou_counts$Minutes_Per_Hour)
var_residence <- sd(kinkajou_counts$Minutes_Per_Hour)
mean_residence_by_region <- group_by(kinkajou_counts_region, Region) %>% dplyr::summarise(Mean = mean(Minutes_Per_Hour), Standard_Deviation =sd(Minutes_Per_Hour))
mean_residence_by_region$Region <- mean_residence_by_region$Region %>% as.character()
mean_residence_by_region <- mean_residence_by_region %>% rbind(c("all", mean_residence, var_residence))
mean_residence_by_region$Units <- "minutes per hour"
mean_residence_by_region

#means and standard deviation of balsa flower
mean_flowers_counts <- mean (flower_counts$Count)
var_flower_counts <- sd(flower_counts$Count)
mean_flower_counts_by_region <- group_by(flower_counts_region, Region) %>% summarise(Mean = mean (Count), Standard_Deviation = sd (Count))
mean_flower_counts_by_region$Region <- mean_flower_counts_by_region$Region %>% as.character()
mean_flower_counts_by_region <- mean_flower_counts_by_region %>% rbind(c("all", mean_flowers_counts, var_flower_counts))
mean_flower_counts_by_region$Units <- "Flowers"
mean_flower_counts_by_region

combined_summary_statistics <- rbind(mean_residence_by_region, mean_flower_counts_by_region)
combined_summary_statistics

paste("mean kinkajou residence in the entire tree, minutes per hour", mean_residence, 
      "standard deviation of kinkajou residence in entire tree, minutes per hour", var_residence,
      "mean flower count in entire tree by day", mean_flowers_counts,
      "standard deviation of mean flower count in entire tree by day", var_flower_counts, sep=" ")
```

```{r regression analysis}

#predicting flower counts based on study night
flowers_regression_all <- lm(data = select(as.data.frame(flower_counts), !geom), formula = Count ~ Study_night)
summary(flowers_regression_all)
#flowers_regression_all

plot(y = predict(flowers_regression_all, newdata = data.frame(Study_night = 0:max(flower_counts$Study_night))), x = 0:max(flower_counts$Study_night), type = "l",
     xlab = "Study Night",
     ylab = "Flower Count",
     main = "Full Tree Flower Count Regression")
points(x = flower_counts$Study_night, y = flower_counts$Count)

plot(x = flower_counts$Study_night, y = flowers_regression_all$residuals,
     xlab = "Study Night",
     ylab = "Residuals",
     main = "Full Tree Flower Count Residuals")
flowers_regression_all$effects

Sflower_all <- sqrt(sum(flowers_regression_all$residuals ^ 2)/(length(flowers_regression_all$residuals) - 2))
qqnorm(flowers_regression_all$residuals/Sflower_all)

#predicting kinkajou residence time based on study night and flower count

residence_regression_all <- lm(data = combined_data, formula = Minutes_Per_Hour ~ Study_night + Count)
summary(residence_regression_all)

#res_reg_all<-lm(data = combined_data, formula = Minutes_Per_Hour ~ Study_night)
#summary(res_reg_all)
# plot(x = combined_data$Study_night, y = combined_data$Minutes_Per_Hour)
# lines(x = combined_data$Study_night, y = residence_regression_all$coefficients["(Intercept)"] + residence_regression_all$coefficients["Study_night"] * combined_data$Study_night)
# 
# plot(x = combined_data$Count, y = combined_data$Minutes_Per_Hour)
# lines(x = combined_data$Count, y = residence_regression_all$coefficients["(Intercept)"] + residence_regression_all$coefficients["Count"] * combined_data$Count)

Sres_all <- sqrt(sum(residence_regression_all$residuals ^ 2)/(length(residence_regression_all$residuals) - 2))
plot(residence_regression_all$residuals,
     xlab = "Index",
     ylab = "Residuals",
     main = "Full Tree Residence Time Residuals")
qqnorm(residence_regression_all$residuals/Sres_all)
```

```{r flower count regression analysis by region}

# using filter function to create new flower data subsets
flowers_R1 <- filter(flower_counts_region, Region == 1) %>% as.data.frame() %>% select(!geom)
flowers_R2 <- filter(flower_counts_region, Region == 2) %>% as.data.frame() %>% select(!geom)
flowers_R3 <- filter(flower_counts_region, Region == 3) %>% as.data.frame() %>% select(!geom)

#predicting flower counts within the regions based on study night

# linear regression flower count region 1
flowers_regression_R1 <- lm(data = flowers_R1, formula = Count ~ Study_night)
summary(flowers_regression_R1)

plot(y = predict(flowers_regression_R1, newdata = data.frame(Study_night = 0:max(flowers_R1$Study_night))), x = 0:max(flowers_R1$Study_night), type = "l",
     xlab = "Study Night",
     ylab = "Flower Count",
     main = "Region 1 Flower Count Regression")
points(x = flowers_R1$Study_night, y = flowers_R1$Count)

plot(x = flowers_R1$Study_night, y = flowers_regression_R1$residuals,
     xlab = "Study Night",
     ylab = "Residuals",
     main = "Region 1 Flower Count Residuals")

Sflower_region1 <- sqrt(sum(flowers_regression_R1$residuals ^ 2)/(length(flowers_regression_R1$residuals) - 2))
qqnorm(flowers_regression_R1$residuals/Sflower_region1)

# linear regression flower count region 2
flowers_regression_R2 <- lm(data = flowers_R2, formula = Count ~ Study_night)
summary(flowers_regression_R2)

plot(y = predict(flowers_regression_R2, newdata = data.frame(Study_night = 0:max(flowers_R2$Study_night))), x = 0:max(flowers_R2$Study_night), type = "l",
     xlab = "Study Night",
     ylab = "Flower Count",
     main = "Region 2 Flower Count Regression")
points(x = flowers_R2$Study_night, y = flowers_R2$Count)

plot(x = flowers_R2$Study_night, y = flowers_regression_R2$residuals,
     xlab = "Study Night",
     ylab = "Residuals",
     main = "Region 2 Flower Count Residuals")

Sflower_region2 <- sqrt(sum(flowers_regression_R2$residuals ^ 2)/(length(flowers_regression_R2$residuals) - 2))
qqnorm(flowers_regression_R2$residuals/Sflower_region2)

# linear regression flower count region 3
flowers_regression_R3 <- lm(data = flowers_R3, formula = Count ~ Study_night)
summary(flowers_regression_R3)

plot(y = predict(flowers_regression_R3, newdata = data.frame(Study_night = 0:max(flowers_R3$Study_night))), x = 0:max(flowers_R3$Study_night), type = "l",
     xlab = "Study Night",
     ylab = "Flower Count",
     main = "Region 3 Flower Count Regression")
points(x = flowers_R3$Study_night, y = flowers_R3$Count)

plot(x = flowers_R3$Study_night, y = flowers_regression_R3$residuals,
     xlab = "Study Night",
     ylab = "Residuals",
     main = "Region 3 Flower Count Residuals")

Sflower_region3 <- sqrt(sum(flowers_regression_R3$residuals ^ 2)/(length(flowers_regression_R3$residuals) - 2))
qqnorm(flowers_regression_R3$residuals/Sflower_region3)
```

```{r residence regression analysis by region}

#predicting kinkajou residence time based on study night and flower count

# combining flower count and residence data containing the regions
combined_data_region <- merge(flower_counts_region, kinkajou_counts_region, by = c("Study_night","Region") , all = TRUE)

R1_data <- filter(combined_data_region, Region == 1)

#linear regression residence time region 1

#R1_Predictions <- predict(residence_region1_regression, newdata = select(R1_data, Count, Study_night))
#plot(x = filter(combined_data_region, Region == 1)$Study_night, y = filter(combined_data_region, Region == 1)$Minutes_Per_Hour, xlab = "Study Night", ylab = "Residence Time", main = "Residence Region 1 Regression") #plot actual residences times by night

#lines(x = filter(combined_data_region, Region == 1)$Study_night, y = R1_Predictions

# residence_region1_regression <- lm(data = R1_data, formula = Minutes_Per_Hour ~ Study_night + Count)
# summary(residence_region1_regression)
# 
# Sres_region1 <- sqrt(sum(residence_region1_regression$residuals ^ 2)/(length(residence_region1_regression$residuals) - 2))
# plot(residence_region1_regression$residuals, xlab = "Index", ylab = "Residuals", main = "Residence Region 1 Regression Residuals")
# qqnorm(residence_region1_regression$residuals/Sres_region1)
# 
# 
# 
# #linear regression residence time region 2
# residence_region2_regression <- lm(data = filter(combined_data_region, Region == 2), formula = Minutes_Per_Hour ~ Study_night + Count)
# summary(residence_region2_regression)
# 
# Sres_region2 <- sqrt(sum(residence_region2_regression$residuals ^ 2)/(length(residence_region2_regression$residuals) - 2))
# plot(residence_region2_regression$residuals, xlab = "Index", ylab = "Residuals", main = "Residence Region 2 Regression Residuals")
# qqnorm(residence_region2_regression$residuals/Sres_region2)
# 
# #linear regression residence time region 3
# residence_region3_regression <- lm(data = filter(combined_data_region, Region == 3), formula = Minutes_Per_Hour ~ Study_night + Count)
# summary(residence_region3_regression)
# 
# Sres_region3 <- sqrt(sum(residence_region3_regression$residuals ^ 2)/(length(residence_region3_regression$residuals) - 2))
# plot(residence_region3_regression$residuals, xlab = "Index", ylab = "Residuals", main = "Residence Region 3 Regression Residuals")
# qqnorm(residence_region3_regression$residuals/Sres_region3)

# combining region regressions into 1 regression
combined_data_region <- mutate(combined_data_region, Total_Flowers = combined_data$Count[pmatch(Study_night, combined_data$Study_night, duplicates.ok = TRUE)])
residence_regression <- lm(data = combined_data_region, formula = Minutes_Per_Hour ~ Count + Region + Total_Flowers)
summary(residence_regression)
# We want to visualize the affect of region and regional flower count, after accounting for the effect of total flower count. TO do this, we substract the modeled effect of total flower count from all of our residence times
combined_data_region = mutate(combined_data_region, Adjusted_Residence = Minutes_Per_Hour - Total_Flowers * residence_regression$coefficients["Total_Flowers"])

ggplot(combined_data_region, aes(x = Count, y = Adjusted_Residence, color = Region)) +
  geom_point() +
  geom_abline(slope = residence_regression$coefficients["Count"], 
            intercept = residence_regression$coefficients["(Intercept)"], colour="firebrick1") + #Region 1
  geom_abline(slope = residence_regression$coefficients["Count"], 
            intercept = (residence_regression$coefficients["(Intercept)"] + residence_regression$coefficients["Region2"]), colour="forestgreen") + #Region 2
  geom_abline(slope = residence_regression$coefficients["Count"], 
            intercept = (residence_regression$coefficients["(Intercept)"] + residence_regression$coefficients["Region3"]), colour="dodgerblue3") + #Region 3
  theme_classic()+
  labs( x = "Regional Flower Count", 
        y = "Adjusted Residence Time")

```
